//
//  Movie.swift
//  Cinetopia
//
//  Created by Rene Girresse on 19/03/24.
//


import Foundation

struct Movie {
    let id: Int
    let title: String
    let image: String
    let synopsis: String
    let rate: Double
    let releaseDate: String
}

let movies: [Movie] = [
    Movie(id: 1, title: "American Psycho", image: "AmericanPsycho", synopsis: "In New York City in 1987, a handsome, young urban professional, Patrick Bateman (Christian Bale), lives a second life as a gruesome serial killer by night. The cast is filled by the detective (Willem Dafoe), the fiance (Reese Witherspoon), the mistress (Samantha Mathis), the coworker (Jared Leto), and the secretary (Chloë Sevigny). This is a biting, wry comedy examining the elements that make a man a monster.", rate: 7.6, releaseDate: "14/04/2000"),
    Movie(id: 2, title: "Bourne Identity", image: "BourneIdentity", synopsis: "The story of a man (Matt Damon), salvaged, near death, from the ocean by an Italian fishing boat. When he recuperates, the man suffers from total amnesia, without identity or background... except for a range of extraordinary talents in fighting, linguistic skills and self-defense that speak of a dangerous past. He sets out on a desperate search-assisted by the initially rebellious Marie (Franka Potente) - to discover who he really is, and why he's being lethally pursued by assassins.", rate: 7.8, releaseDate: "14/06/2002"),
    Movie(id: 3, title: "Django Unchained", image: "Django", synopsis: "Two years before the Civil War, Django (Jamie Foxx), a slave, finds himself accompanying an unorthodox German bounty hunter named Dr. King Schultz (Christoph Waltz) on a mission to capture the vicious Brittle brothers. Their mission successful, Schultz frees Django, and together they hunt the South's most-wanted criminals. Their travels take them to the infamous plantation of shady Calvin Candie (Leonardo DiCaprio), where Django's long-lost wife (Kerry Washington) is still a slave.", rate: 8.5, releaseDate: "25/12/2012"),
    Movie(id: 4, title: "Drive", image: "Drive", synopsis: "Driver is a skilled Hollywood stuntman who moonlights as a getaway driver for criminals. Though he projects an icy exterior, lately he's been warming up to a pretty neighbor named Irene and her young son, Benicio. When Irene's husband gets out of jail, he enlists Driver's help in a million-dollar heist. The job goes horribly wrong, and Driver must risk his life to protect Irene and Benicio from the vengeful masterminds behind the robbery.", rate: 7.8, releaseDate: "16/09/2011"),
    Movie(id: 5, title: "Elvis", image: "Elvis", synopsis: "From his rise to fame to his unprecedented superstardom, rock 'n' roll icon Elvis Presley maintains a complicated relationship with his enigmatic manager, Colonel Tom Parker, over the course of 20 years. Central to Presley's journey and happiness is one of the most influential people in his life -- Priscilla.", rate: 7.3, releaseDate: "24/06/2022"),
    Movie(id: 6, title: "Fight Club", image: "FightClub", synopsis: "A depressed man (Edward Norton) suffering from insomnia meets a strange soap salesman named Tyler Durden (Brad Pitt) and soon finds himself living in his squalid house after his perfect apartment is destroyed. The two bored men form an underground club with strict rules and fight other men who are fed up with their mundane lives. Their perfect partnership frays when Marla (Helena Bonham Carter), a fellow support group crasher, attracts Tyler's attention.", rate: 8.8, releaseDate: "15/10/1999"),
    Movie(id: 7, title: "Forrest Gump", image: "ForrestGump", synopsis: "Slow-witted Forrest Gump (Tom Hanks) has never thought of himself as disadvantaged, and thanks to his supportive mother (Sally Field), he leads anything but a restricted life. Whether dominating on the gridiron as a college football star, fighting in Vietnam or captaining a shrimp boat, Forrest inspires people with his childlike optimism. But one person Forrest cares about most may be the most difficult to save -- his childhood love, the sweet but troubled Jenny (Robin Wright).", rate: 8.8, releaseDate: "06/07/1994"),
    Movie(id: 8, title: "Fury", image: "Fury", synopsis: "In April 1945, the Allies are making their final push in the European theater. A battle-hardened Army sergeant named Don Wardaddy Collier (Brad Pitt), leading a Sherman tank and a five-man crew, undertakes a deadly mission behind enemy lines. Hopelessly outnumbered, outgunned and saddled with an inexperienced soldier (Logan Lerman) in their midst, Wardaddy and his men face overwhelming odds as they move to strike at the heart of Nazi Germany.", rate: 7.6, releaseDate: "17/10/2014"),
    Movie(id: 9, title: "GoodFellas", image: "GoodFellas", synopsis: "A young man grows up in the mob and works very hard to advance himself through the ranks. He enjoys his life of money and luxury, but is oblivious to the horror that he causes. A drug addiction and a few mistakes ultimately unravel his climb to the top. Based on the book Wiseguy by Nicholas Pileggi.", rate: 8.7, releaseDate: "19/09/1990"),
    Movie(id: 10, title: "Good Will Hunting", image: "GoodWillHunting", synopsis: "Will Hunting (Matt Damon) has a genius-level IQ but chooses to work as a janitor at MIT. When he solves a difficult graduate-level math problem, his talents are discovered by Professor Gerald Lambeau (Stellan Skarsgard), who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he will get treatment from therapist Sean Maguire (Robin Williams).", rate: 8.3, releaseDate: "05/12/1997"),
    Movie(id: 11, title: "Great Expectations", image: "GreatExpectations", synopsis: "This modern adaptation of Dickens' classic coming of age story sees the young and naïve Finn, who falls in love with Estella, a girl raised with the strict intention of breaking men's hearts. When he is grown up and living in New York, having become a successful painter, Estella reappears in his life and Finn falls deeply in love, knowing all the while that it is a feeling that can never be returned.", rate: 6.8, releaseDate: "30/01/1998"),
    Movie(id: 12, title: "Green Mile", image: "GreenMile", synopsis: "Paul Edgecomb (Tom Hanks) walked the mile with a variety of cons. He had never encountered someone like John Coffey (Michael Clarke Duncan), a massive black man convicted of brutally killing a pair of young sisters. Coffey had the size and strength to kill anyone, but not the demeanor. Beyond his simple, naive nature and a deathly fear of the dark, Coffey seemed to possess a prodigious, supernatural gift. Paul began to question whether Coffey was truly guilty of murdering the two girls.", rate: 8.6, releaseDate: "10/12/1999"),
    Movie(id: 13, title: "The Hateful Eight", image: "HatefulEight", synopsis: "While racing toward the town of Red Rock in post-Civil War Wyoming, bounty hunter John The Hangman Ruth (Kurt Russell) and his fugitive prisoner (Jennifer Jason Leigh) encounter another bounty hunter (Samuel L. Jackson) and a man who claims to be a sheriff. Hoping to find shelter from a blizzard, the group travels to a stagecoach stopover located on a mountain pass. Greeted there by four strangers, the eight travelers soon learn that they may not make it to their destination after all.", rate: 7.8, releaseDate: "30/12/2015"),
    Movie(id: 14, title: "American History X", image: "HistoryX", synopsis: "Living a life marked by violence and racism, neo-Nazi Derek Vinyard (Edward Norton) finally goes to prison after killing two black youths who tried to steal his car. Upon his release, Derek vows to change his ways; he hopes to prevent his younger brother, Danny (Edward Furlong), who idolizes Derek, from following in his footsteps. As he struggles with his own deeply ingrained prejudices and watches their mother grow sicker, Derek wonders if his family can overcome a lifetime of hate.", rate: 8.5, releaseDate: "30/10/1998"),
    Movie(id: 15, title: "Inglourious Basterds", image: "inglorious", synopsis: "It is the first year of Germany's occupation of France. Allied officer Lt. Aldo Raine (Brad Pitt) assembles a team of Jewish soldiers to commit violent acts of retribution against the Nazis, including the taking of their scalps. He and his men join forces with Bridget von Hammersmark, a German actress and undercover agent, to bring down the leaders of the Third Reich. Their fates converge with theater owner Shosanna Dreyfus, who seeks to avenge the Nazis' execution of her family.", rate: 8.4, releaseDate: "21/08/2009"),
    Movie(id: 16, title: "Interview with the vampire", image: "Interview", synopsis: "Born as an 18th-century lord, Louis is now a bicentennial vampire, telling his story to an eager biographer. Suicidal after the death of his family, he meets Lestat, a vampire who persuades him to choose immortality over death and become his companion. Eventually, gentle Louis resolves to leave his violent maker, but Lestat guilts him into staying by turning a young girl -- whose addition to the family breeds even more conflict.", rate: 7.5, releaseDate: "11/11/1994"),
    Movie(id: 17, title: "Kill Bill: Volume 1", image: "KillBill", synopsis: "A former assassin, known simply as The Bride (Uma Thurman), wakes from a coma four years after her jealous ex-lover Bill (David Carradine) attempts to murder her on her wedding day. Fueled by an insatiable desire for revenge, she vows to get even with every person who contributed to the loss of her unborn child, her entire wedding party, and four years of her life. After devising a hit list, The Bride sets off on her quest, enduring unspeakable injury and unscrupulous enemies.", rate: 8.2, releaseDate: "10/10/2003"),
    Movie(id: 18, title: "Mad Max: Fury Road", image: "MadMax", synopsis: "Years after the collapse of civilization, the tyrannical Immortan Joe enslaves apocalypse survivors inside the desert fortress the Citadel. When the warrior Imperator Furiosa (Charlize Theron) leads the despot's five wives in a daring escape, she forges an alliance with Max Rockatansky (Tom Hardy), a loner and former captive. Fortified in the massive, armored truck the War Rig, they try to outrun the ruthless warlord and his henchmen in a deadly high-speed chase through the Wasteland.", rate: 8.1, releaseDate: "15/05/2015"),
    Movie(id: 19, title: "Matrix", image: "Matrix", synopsis: "Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.", rate: 8.7, releaseDate: "31/03/1999"),
    Movie(id: 20, title: "Once upon a time in Hollywood", image: "Once upon a time", synopsis: "Actor Rick Dalton gained fame and fortune by starring in a 1950s television Western, but is now struggling to find meaningful work in a Hollywood that he doesn't recognize anymore. He spends most of his time drinking and palling around with Cliff Booth, his easygoing best friend and longtime stunt double. Rick also happens to live next door to Roman Polanski and Sharon Tate -- the filmmaker and budding actress whose futures will forever be altered by members of the Manson Family.", rate: 7.6, releaseDate: "26/07/2019"),
    Movie(id: 21, title: "Pulp Fiction", image: "Pulp-Fiction", synopsis: "Vincent Vega (John Travolta) and Jules Winnfield (Samuel L. Jackson) are hitmen with a penchant for philosophical discussions. In this ultra-hip, multi-strand crime movie, their storyline is interwoven with those of their boss, gangster Marsellus Wallace (Ving Rhames) ; his actress wife, Mia (Uma Thurman) ; struggling boxer Butch Coolidge (Bruce Willis) ; master fixer Winston Wolfe (Harvey Keitel) and a nervous pair of armed robbers, Pumpkin (Tim Roth) and Honey Bunny (Amanda Plummer).", rate: 8.9, releaseDate: "14/10/1994"),
    Movie(id: 22, title: "Saving Private Ryan", image: "SavingPrivateRyan", synopsis: "Captain John Miller (Tom Hanks) takes his men behind enemy lines to find Private James Ryan, whose three brothers have been killed in combat. Surrounded by the brutal realties of war, while searching for Ryan, each man embarks upon a personal journey and discovers their own strength to triumph over an uncertain future with honor, decency and courage.", rate: 8.6, releaseDate: "24/07/1998"),
    Movie(id: 23, title: "Seven", image: "seven", synopsis: "When retiring police Detective William Somerset (Morgan Freeman) tackles a final case with the aid of newly transferred David Mills (Brad Pitt), they discover a number of elaborate and grizzly murders. They soon realize they are dealing with a serial killer (Kevin Spacey) who is targeting people he thinks represent one of the seven deadly sins. Somerset also befriends Mills' wife, Tracy (Gwyneth Paltrow), who is pregnant and afraid to raise her child in the crime-riddled city.", rate: 8.6, releaseDate: "22/09/1995"),
    Movie(id: 24, title: "The shawshank redemption", image: "ShawShank", synopsis: "Andy Dufresne (Tim Robbins) is sentenced to two consecutive life terms in prison for the murders of his wife and her lover and is sentenced to a tough prison. However, only Andy knows he didn't commit the crimes. While there, he forms a friendship with Red (Morgan Freeman), experiences brutality of prison life, adapts, helps the warden, etc., all in 19 years.", rate: 9.3, releaseDate: "23/09/1994"),
    Movie(id: 25, title: "The silence of the lambs", image: "Silence", synopsis: "Jodie Foster stars as Clarice Starling, a top student at the FBI's training academy. Jack Crawford (Scott Glenn) wants Clarice to interview Dr. Hannibal Lecter (Anthony Hopkins), a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.", rate: 8.6, releaseDate: "14/02/1991"),
    Movie(id: 26, title: "The sixth sense", image: "SixthSense", synopsis: "Young Cole Sear (Haley Joel Osment) is haunted by a dark secret: he is visited by ghosts. Cole is frightened by visitations from those with unresolved problems who appear from the shadows. He is too afraid to tell anyone about his anguish, except child psychologist Dr. Malcolm Crowe (Bruce Willis). As Dr. Crowe tries to uncover the truth about Cole's supernatural abilities, the consequences for client and therapist are a jolt that awakens them both to something unexplainable.", rate: 8.2, releaseDate: "06/08/1999"),
    Movie(id: 27, title: "The lord of the rings: The fellowship of the ring", image: "The-Lord-of-the-Rings", synopsis: "The future of civilization rests in the fate of the One Ring, which has been lost for centuries. Powerful forces are unrelenting in their search for it. But fate has placed it in the hands of a young Hobbit named Frodo Baggins (Elijah Wood), who inherits the Ring and steps into legend. A daunting task lies ahead for Frodo when he becomes the Ringbearer - to destroy the One Ring in the fires of Mount Doom where it was forged.", rate: 8.9, releaseDate: "19/12/2001"),
    Movie(id: 28, title: "The Departed", image: "TheDeparted", synopsis: "South Boston cop Billy Costigan (Leonardo DiCaprio) goes under cover to infiltrate the organization of gangland chief Frank Costello (Jack Nicholson). As Billy gains the mobster's trust, a career criminal named Colin Sullivan (Matt Damon) infiltrates the police department and reports on its activities to his syndicate bosses. When both organizations learn they have a mole in their midst, Billy and Colin must figure out each other's identities to save their own lives.", rate: 8.5, releaseDate: "06/10/2006"),
    Movie(id: 29, title: "V for vendetta", image: "Vendetta", synopsis: "Following world war, London is a police state occupied by a fascist government, and a vigilante known only as V (Hugo Weaving) uses terrorist tactics to fight the oppressors of the world in which he now lives. When V saves a young woman named Evey (Natalie Portman) from the secret police, he discovers an ally in his fight against England's oppressors.", rate: 8.2, releaseDate: "03/17/2006"),
    Movie(id: 30, title: "X-Men: First Class", image: "X-Men", synopsis: "In the early 1960s, during the height of the Cold War, a mutant named Charles Xavier (James McAvoy) meets a fellow mutant named Erik Lehnsherr (Michael Fassbender). Despite their vastly different backgrounds -- Charles grew up with a wealthy family, while Erik lost his parents at Auschwitz -- the two become close friends. As the world teeters on the brink of a nuclear war, Charles and Erik with other mutants join forces to save humanity. However, a situation soon tears the friends apart.", rate: 7.7, releaseDate: "03/06/2011"),
]
